on:
  push:
    branches:
      - main

jobs:
  meow:
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        project: [avatar_emoji_bot, flexdo, smeshariki]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: GHCR login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ matrix.project }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: examples/${{ matrix.project }}/Dockerfile
      - name: Deploy
        env:
          POMOGITE: ${{ secrets.POMOGITE }}
        run: |
          curl --request POST \
               --url https://vhap-update.vanutp.dev/update \
               --header "Content-Type: application/json" \
               --data '{"key":"'$POMOGITE'"}' \
               --fail
